databases:
  - name: deshevshe-postgres
    databaseName: deshevshe
    user: deshevshe
    plan: free

services:
  - type: web
    name: deshevshe-kg
    env: node
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: deshevshe-postgres
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "false"
      - key: PORT
        value: 10000